{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "comfyui-helm.serviceAccountName" . }}
  labels:
    {{- include "comfyui-helm.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.serviceAccount.automount }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
  {{- end }}
{{- end }}
